# Generated by Django 6.0.2 on 2026-03-06 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
